### ISSUE TITLE
Allow arbitrary expressions in quotations for ClientSide

### ISSUE THREAD

**Issue by Tarmil** [dotnet-websharper/websharper#853]
Compile the contents to a top-level function instead of just looking up the address of the called function.

**Comment by Jand42** [comment]
This needs a fix: class entries are created outside Resolve method for these translated quotations, which throws an error during Resolve if the containing class/module contains any other kind of WS-related member (for example a remote method).

Also: Resolve sets up dependency on the AssemblyNode correctly, not having this also caused an error when a Sitelet page uses code from current assembly only through an event handler.

**Comment by Jand42** [comment]
Reopening as this was not merged in for 4.1.0.171 release fully (only the compiler support, to event handlers using custom code, but not `ctx.ClientSide`).

Also: C# equivalent is missing. Needs similar compiler support for exploring server-side code and registering argument expressions to translate. Helper functions probably will need to use arguments with `CallerFilePath` and `CallerLineNumber` attributes, so that the runtime can look up the translated version of the expression.

**Comment by Jand42** [comment]
Initial addition of a `ctx.ClientSide` (extension method on the `Context` type) has now been removed, as `ClientSide` works equivalently.

**Comment by Jand42** [comment]
A minor optimization is possible: if there are no captured arguments, the runtime should not look for any.
